FROM registry.svc.ci.openshift.org/ocp/builder:golang-1.10 AS builder

ADD . /usr/src/app-netutil

WORKDIR /usr/src/app-netutil

RUN make clean && make build

FROM registry.svc.ci.openshift.org/ocp/4.0:base

COPY --from=builder /usr/src/app-netutil/bin/server /usr/bin/
COPY --from=builder /usr/src/app-netutil/bin/client /usr/bin/

WORKDIR /

LABEL io.k8s.display-name="OpenShift Application Network Utility"

CMD ["/usr/bin/server"]
