apiVersion: v1
kind: Pod
metadata:
  name: sriov-pod-1
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-net-a, sriov-net-b
spec:
  containers:
  - name: dpdk-app
    image: dpdk-app-centos:latest
    imagePullPolicy: Never
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/podnetinfo
      name: podnetinfo
      readOnly: false
    - mountPath: /dev/hugepages
      name: hugepage
    resources:
      requests:
        memory: 1Gi
        #memory: 2Mi
        #cpu: "4"
        intel.com/intel_sriov_dpdk_a: '1'
        intel.com/intel_sriov_dpdk_b: '1'
      limits:
        hugepages-1Gi: 2Gi
        #hugepages-2Mi: 2048Mi
        #cpu: "4"
        intel.com/intel_sriov_dpdk_a: '1'
        intel.com/intel_sriov_dpdk_b: '1'
    # Uncomment to control which DPDK App is running in container.
    # If not provided, l3fwd is default.
    #   Options: l2fwd l3fwd testpmd
    #env:
    #- name: DPDK_SAMPLE_APP
    #  value: "l2fwd"
    #
    # Uncomment to debug DPDK App or to run manually to change
    # DPDK command line options.
    #command: ["sleep", "infinity"]
  volumes:
  - name: podnetinfo
    downwardAPI:
      items:
        - path: "labels"
          fieldRef:
            fieldPath: metadata.labels
        - path: "annotations"
          fieldRef:
            fieldPath: metadata.annotations
        - path: "hugepageSize"
          resourceFieldRef:
            containerName: dpdk-app
            resource: requests.memory
            divisor: 1Mi
  - name: hugepage
    emptyDir:
      medium: HugePages
